version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: puppy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: puppy-postgres
    environment:
      POSTGRES_DB: puppy_project_db
      POSTGRES_USER: yuqiye
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
